# Generated by Django 3.2.5 on 2021-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_field', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
